# Generated by Django 4.0.5 on 2022-11-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Emp_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Emp_name', models.CharField(max_length=255)),
                ('emp_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UpdateDeleteoperation.department')),
            ],
        ),
    ]
